wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.7
    start_time: 1664617586.294867
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.7
      5: 0.13.3
      8:
      - 1
      - 3
      - 5
gamma:
  desc: null
  value: 0.95
theta:
  desc: null
  value: 1.0e-07
